# Generated by Django 5.1.5 on 2025-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11045_generate_resource_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tilemodel",
            name="data",
            field=models.JSONField(blank=True, db_column="tiledata", default=dict),
        ),
    ]
